openapi: 3.0.1
info:
  title: Shell Command Plugin
  description: A plugin that allows the user to execute shell commands using ChatGPT.
  version: v1
servers:
  - url: http://localhost:3333
paths:
  /run:
    post:
      operationId: runCommand
      summary: Execute a shell command
      requestBody:
        description: The JSON object containing the shell commands to execute
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                commands:
                  type: array
                  items:
                    type: string
                  description: An array of shell commands to execute.  Can provide multiple commands or chain commands one after another.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/runCommandResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
components:
  schemas:
    runCommandResponse:
      type: object
      properties:
        output:
          type: array
          items:
            type: string
          description: The output of the shell command as a list of lines.
        error:
          type: array
          items:
            type: string
          description: The error output of the shell command as a list of lines.
    errorResponse:
      type: object
      properties:
        error:
          type: string
          description: The error message, if any.
